dw_hr:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DW_POSTGRES_HOST') }}"
      user: "{{ env_var('DW_POSTGRES_USER') }}"
      password: "{{ env_var('DW_POSTGRES_PASSWORD') }}"
      port: "{{ env_var('DW_POSTGRES_PORT') | int }}"
      dbname: "{{ env_var('DW_POSTGRES_DB') }}"
      schema: analytics
      threads: 4